const constants = {};

/* SIGNIN */
constants['SIGNIN_PENDING'] = 'AUTH/SIGNIN_PENDING';
constants['SIGNIN_SUCCESS'] = 'AUTH/SIGNIN_SUCCESS';
constants['SIGNIN_ERROR'] = 'AUTH/SIGNIN_ERROR';

/* EDIT ERROR MESSAGE */
constants['EDIT_ERROR_MESSAGE'] = 'AUTH/EDIT_ERROR_MESSAGE';

/* IMPERSONATE */
constants['IMPERSONATE_PENDING'] = 'AUTH/IMPERSONATE_PENDING';
constants['IMPERSONATE_SUCCESS'] = 'AUTH/IMPERSONATE_SUCCESS';
constants['IMPERSONATE_ERROR'] = 'AUTH/IMPERSONATE_ERROR';

/* FACEBOOK_SIGNIN */
constants['FACEBOOK_SIGNIN_PENDING'] = 'AUTH/FACEBOOK_SIGNIN_PENDING';
constants['FACEBOOK_SIGNIN_SUCCESS'] = 'AUTH/FACEBOOK_SIGNIN_SUCCESS';
constants['FACEBOOK_SIGNIN_ERROR'] = 'AUTH/FACEBOOK_SIGNIN_ERROR';

/* GOOGLE_SIGNIN */
constants['GOOGLE_SIGNIN_PENDING'] = 'AUTH/GOOGLE_SIGNIN_PENDING';
constants['GOOGLE_SIGNIN_SUCCESS'] = 'AUTH/GOOGLE_SIGNIN_SUCCESS';
constants['GOOGLE_SIGNIN_ERROR'] = 'AUTH/GOOGLE_SIGNIN_ERROR';

/* SIGNOUT */
constants['SIGNOUT_PENDING'] = 'AUTH/SIGNOUT_PENDING';
constants['SIGNOUT_SUCCESS'] = 'AUTH/SIGNOUT_SUCCESS';
constants['SIGNOUT_ERROR'] = 'AUTH/SIGNOUT_ERROR';
constants['EDIT_USER'] = 'AUTH/EDIT_USER';

/* REGISTER */
constants['REGISTER_PENDING'] = 'AUTH/REGISTER_PENDING';
constants['REGISTER_SUCCESS'] = 'AUTH/REGISTER_SUCCESS';
constants['REGISTER_ERROR'] = 'AUTH/REGISTER_ERROR';
constants['SET_DATA_FROM_TOKEN'] = 'AUTH/SET_DATA_FROM_TOKEN';

/* FORGOT */
constants['FORGOT_PENDING'] = 'AUTH/FORGOT_PENDING';
constants['FORGOT_SUCCESS'] = 'AUTH/FORGOT_SUCCESS';
constants['FORGOT_ERROR'] = 'AUTH/FORGOT_ERROR';

/* RESET_PASSWORD */
constants['RESET_PASSWORD_PENDING'] = 'AUTH/RESET_PASSWORD_PENDING';
constants['RESET_PASSWORD_SUCCESS'] = 'AUTH/RESET_PASSWORD_SUCCESS';
constants['RESET_PASSWORD_ERROR'] = 'AUTH/RESET_PASSWORD_ERROR';

constants['CLOSE_ACCOUNT_PENDING'] = 'AUTH/CLOSE_ACCOUNT_PENDING';
constants['CLOSE_ACCOUNT_SUCCESS'] = 'AUTH/CLOSE_ACCOUNT_SUCCESS';
constants['CLOSE_ACCOUNT_ERROR'] = 'AUTH/CLOSE_ACCOUNT_ERROR';

/* RESET SUCCESS/ERROR MESSAGES */
constants['RESET_MESSAGES_SUCCESS'] = 'AUTH/RESET_MESSAGES_SUCCESS';

export default constants;
